
server.port=8088

# Configuration for euraka server
euraka.client.service-url.defaultZone=http://service-registry:8761/eureka/
euraka.instance.prefer-ip-address=true

#RabbitMQ configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# spring.rabbitmq.queue=demande.queue
# spring.rabbitmq.exchange=demande.exchange
# spring.rabbitmq.routingKey=demande.routingKey

# demande.exchange=demande.exchange
# decision.exchange=decision.exchange
# demande.queue=demande.queue
# approved.routingkey=demande.approved
# rejected.routingkey=demande.rejected