
server.port=8090

# Configuration for eureka server
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.instance.prefer-ip-address=true

#RabbitMQ configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# spring.rabbitmq.queue=demande.queue
# spring.rabbitmq.exchange=demande.exchange
# spring.rabbitmq.routingKey=demande.create
